// this is very simple library, the goal is partitioning sdb

use serde::{Deserialize, Serialize};
use std::vec::Vec;

#[derive(Serialize, Deserialize, Debug)]
struct DiskInfo {
    number: u32,
    #[serde(rename(serialize = "diskPath"))]
    disk_path: String,
    path: String,
    mountpoint: Option<String>,
    filesystem: String,
    format: bool,
    start: u64,
    end: u64,
    size: u64,
    autogenerated: bool,
}

struct Partgen;

impl Partgen {
    fn readjson() -> Vec<DiskInfo>
}